import { Priority, type Category } from '@/types';

export const RADIO_COLORS = [
  '#3b82f6',
  '#8b5cf6',
  '#10b981',
  '#f59e0b',
  '#ef4444',
  '#ec4899',
  '#06b6d4',
  '#6366f1',
  '#84cc16',
  '#f97316',
] as const;

export const PRIORITY_CONFIG = {
  [Priority.Easy]: { label: 'Easy', color: '#00c7be' },
  [Priority.Medium]: { label: 'Medium', color: '#ff9500' },
  [Priority.Hard]: { label: 'Hard', color: '#ff453a' },
} as const;

export const SORT_OPTIONS = [
  { value: 'newest', label: 'Newest' },
  { value: 'oldest', label: 'Oldest' },
  { value: 'percentage', label: 'Percentage' },
] as const;

export type SortOption = (typeof SORT_OPTIONS)[number]['value'];

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-001',
    name: 'Frontend Essentials',
    slug: 'frontend-essentials',
    noteCount: 10,
    categoryColor: '#3b82f6',
    categoryNotes: [
      {
        id: 'n1-1',
        tags: ['vue', 'composition-api'],
        title: 'Mastering Provide/Inject',
        pinned: true,
        content: 'Deep dive into InjectionKey typing for robust dependency injection.',
        completed: false,
        priority: Priority.Hard,
        categoryId: 'cat-001',
        archived: false,
        categoryColor: '#3b82f6',
        createdAt: '2026-04-25T10:00:00Z',
        updatedAt: '2026-04-25T10:00:00Z',
      },
      {
        id: 'n1-2',
        tags: ['css', 'ui-design'],
        title: 'Timeline Component Styling',
        pinned: false,
        content: 'Implement dynamic CSS variables for category colors.',
        completed: true,
        priority: Priority.Medium,
        categoryId: 'cat-001',
        archived: false,
        categoryColor: '#3b82f6',
        createdAt: '2026-04-25T08:30:00Z',
        updatedAt: '2026-04-25T09:15:00Z',
      },
      {
        id: 'n1-3',
        tags: ['performance'],
        title: 'Vite Build Optimization',
        pinned: false,
        content: 'Analyze bundle size and configure manual chunks.',
        completed: false,
        priority: Priority.Hard,
        categoryId: 'cat-001',
        archived: false,
        categoryColor: '#3b82f6',
        createdAt: '2026-04-25T06:00:00Z',
        updatedAt: '2026-04-25T06:00:00Z',
      },
      {
        id: 'n1-4',
        tags: ['ts'],
        title: 'Refactor Utility Types',
        pinned: false,
        content: 'Clean up Pick and Omit usage across the data layer.',
        completed: false,
        priority: Priority.Medium,
        categoryId: 'cat-001',
        archived: false,
        categoryColor: '#3b82f6',
        createdAt: '2026-04-25T04:20:00Z',
        updatedAt: '2026-04-25T04:20:00Z',
      },
      {
        id: 'n1-5',
        tags: ['api'],
        title: 'Define API Interfaces',
        pinned: false,
        content: 'Create global DTOs for synchronization service.',
        completed: true,
        priority: Priority.Hard,
        categoryId: 'cat-001',
        archived: false,
        categoryColor: '#3b82f6',
        createdAt: '2026-04-24T15:00:00Z',
        updatedAt: '2026-04-24T16:30:00Z',
      },
      {
        id: 'n1-6',
        tags: ['refactoring'],
        title: 'Extract Validation Logic',
        pinned: false,
        content: 'Move form validation to useFormValidation composable.',
        completed: false,
        priority: Priority.Easy,
        categoryId: 'cat-001',
        archived: false,
        categoryColor: '#3b82f6',
        createdAt: '2026-04-24T11:45:00Z',
        updatedAt: '2026-04-24T11:45:00Z',
      },
      {
        id: 'n1-7',
        tags: ['figma'],
        title: 'Design System Update',
        pinned: false,
        content: 'Sync icon variants with latest Figma design tokens.',
        completed: true,
        priority: Priority.Medium,
        categoryId: 'cat-001',
        archived: false,
        categoryColor: '#3b82f6',
        createdAt: '2026-04-24T09:00:00Z',
        updatedAt: '2026-04-24T09:00:00Z',
      },
      {
        id: 'n1-8',
        tags: ['git'],
        title: 'Husky Hooks Config',
        pinned: false,
        content: 'Setup pre-commit hooks for ESLint and Prettier.',
        completed: true,
        priority: Priority.Easy,
        categoryId: 'cat-001',
        archived: false,
        categoryColor: '#3b82f6',
        createdAt: '2026-04-22T14:10:00Z',
        updatedAt: '2026-04-22T14:10:00Z',
      },
      {
        id: 'n1-9',
        tags: ['testing'],
        title: 'Unit Test Setup',
        pinned: false,
        content: 'Initialize Vitest for core business logic.',
        completed: false,
        priority: Priority.Hard,
        categoryId: 'cat-001',
        archived: false,
        categoryColor: '#3b82f6',
        createdAt: '2026-04-22T10:00:00Z',
        updatedAt: '2026-04-22T10:00:00Z',
      },
      {
        id: 'n1-10',
        tags: ['architecture'],
        title: 'Pinia Store Structure',
        pinned: false,
        content: 'Finalize the Pinia store hierarchy for the app.',
        completed: true,
        priority: Priority.Medium,
        categoryId: 'cat-001',
        archived: false,
        categoryColor: '#3b82f6',
        createdAt: '2026-04-20T13:00:00Z',
        updatedAt: '2026-04-20T13:00:00Z',
      },
    ],
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-04-20T14:30:00Z',
  },
  {
    id: 'cat-002',
    name: 'TypeScript Deep Dive',
    slug: 'typescript-deep-dive',
    noteCount: 10,
    categoryColor: '#8b5cf6',
    categoryNotes: [
      {
        id: 'n2-1',
        tags: ['ts', 'generics'],
        title: 'Generic Constraints',
        pinned: true,
        content: 'Understanding "extends" in generic types for better API responses.',
        completed: false,
        priority: Priority.Hard,
        categoryId: 'cat-002',
        archived: false,
        categoryColor: '#8b5cf6',
        createdAt: '2026-04-26T09:00:00Z',
        updatedAt: '2026-04-26T09:00:00Z',
      },
      {
        id: 'n2-2',
        tags: ['ts', 'advanced'],
        title: 'Mapped Types',
        pinned: false,
        content: 'Create a Readonly variant of existing interfaces using Mapped Types.',
        completed: true,
        priority: Priority.Medium,
        categoryId: 'cat-002',
        archived: false,
        categoryColor: '#8b5cf6',
        createdAt: '2026-04-26T10:00:00Z',
        updatedAt: '2026-04-26T11:00:00Z',
      },
      {
        id: 'n2-3',
        tags: ['ts'],
        title: 'Type Guards vs Assertions',
        pinned: false,
        content: 'Refactor "as" assertions to proper "is" type guards.',
        completed: false,
        priority: Priority.Hard,
        categoryId: 'cat-002',
        archived: false,
        categoryColor: '#8b5cf6',
        createdAt: '2026-04-26T12:00:00Z',
        updatedAt: '2026-04-26T12:00:00Z',
      },
      {
        id: 'n2-4',
        tags: ['ts', 'oop'],
        title: 'Abstract Classes',
        pinned: false,
        content: 'When to use abstract classes over interfaces for base services.',
        completed: false,
        priority: Priority.Medium,
        categoryId: 'cat-002',
        archived: false,
        categoryColor: '#8b5cf6',
        createdAt: '2026-04-26T14:00:00Z',
        updatedAt: '2026-04-26T14:00:00Z',
      },
      {
        id: 'n2-5',
        tags: ['ts'],
        title: 'Template Literal Types',
        pinned: false,
        content: 'Generate dynamic event names like "onUpdate" using template literals.',
        completed: true,
        priority: Priority.Easy,
        categoryId: 'cat-002',
        archived: false,
        categoryColor: '#8b5cf6',
        createdAt: '2026-04-25T15:00:00Z',
        updatedAt: '2026-04-25T15:00:00Z',
      },
      {
        id: 'n2-6',
        tags: ['ts', 'config'],
        title: 'tsconfig Strict Mode',
        pinned: false,
        content: 'Resolve all "implicit any" errors after enabling strict: true.',
        completed: true,
        priority: Priority.Hard,
        categoryId: 'cat-002',
        archived: false,
        categoryColor: '#8b5cf6',
        createdAt: '2026-04-25T11:00:00Z',
        updatedAt: '2026-04-25T13:00:00Z',
      },
      {
        id: 'n2-7',
        tags: ['ts'],
        title: 'Utility Types: Required',
        pinned: false,
        content: 'Use Required<T> for form submission validation logic.',
        completed: false,
        priority: Priority.Easy,
        categoryId: 'cat-002',
        archived: false,
        categoryColor: '#8b5cf6',
        createdAt: '2026-04-24T08:00:00Z',
        updatedAt: '2026-04-24T08:00:00Z',
      },
      {
        id: 'n2-8',
        tags: ['ts', 'patterns'],
        title: 'Discriminated Unions',
        pinned: false,
        content: 'Handle API error vs success states with discriminated unions.',
        completed: true,
        priority: Priority.Medium,
        categoryId: 'cat-002',
        archived: false,
        categoryColor: '#8b5cf6',
        createdAt: '2026-04-24T10:00:00Z',
        updatedAt: '2026-04-24T10:00:00Z',
      },
      {
        id: 'n2-9',
        tags: ['ts'],
        title: 'Declaration Merging',
        pinned: false,
        content: 'Extend Window interface for third-party analytics scripts.',
        completed: false,
        priority: Priority.Medium,
        categoryId: 'cat-002',
        archived: false,
        categoryColor: '#8b5cf6',
        createdAt: '2026-04-23T16:00:00Z',
        updatedAt: '2026-04-23T16:00:00Z',
      },
      {
        id: 'n2-10',
        tags: ['ts', 'learning'],
        title: 'Covariance vs Contravariance',
        pinned: false,
        content: 'Deep dive into function type compatibility in TS.',
        completed: false,
        priority: Priority.Hard,
        categoryId: 'cat-002',
        archived: false,
        categoryColor: '#8b5cf6',
        createdAt: '2026-04-22T09:00:00Z',
        updatedAt: '2026-04-22T09:00:00Z',
      },
    ],
    createdAt: '2026-02-10T09:15:00Z',
    updatedAt: '2026-04-22T11:00:00Z',
  },
  {
    id: 'cat-003',
    name: 'Vue 3 Composition',
    slug: 'vue-3-composition',
    noteCount: 10,
    categoryColor: '#10b981',
    categoryNotes: [
      {
        id: 'n3-1',
        tags: ['vue', 'reactive'],
        title: 'ref vs reactive',
        pinned: true,
        content: 'Documenting when to use reactive() for complex objects.',
        completed: true,
        priority: Priority.Easy,
        categoryId: 'cat-003',
        archived: false,
        categoryColor: '#10b981',
        createdAt: '2026-04-27T08:00:00Z',
        updatedAt: '2026-04-27T08:00:00Z',
      },
      {
        id: 'n3-2',
        tags: ['vue', 'composables'],
        title: 'Custom Mouse Tracker',
        pinned: false,
        content: 'Build a reusable useMouse composable with cleanup logic.',
        completed: false,
        priority: Priority.Medium,
        categoryId: 'cat-003',
        archived: false,
        categoryColor: '#10b981',
        createdAt: '2026-04-27T10:00:00Z',
        updatedAt: '2026-04-27T10:00:00Z',
      },
      {
        id: 'n3-3',
        tags: ['vue', 'lifecycle'],
        title: 'onWatcherCleanup',
        pinned: false,
        content: 'Using the new Vue 3.5 feature for efficient watcher cleanup.',
        completed: false,
        priority: Priority.Hard,
        categoryId: 'cat-003',
        archived: false,
        categoryColor: '#10b981',
        createdAt: '2026-04-27T12:00:00Z',
        updatedAt: '2026-04-27T12:00:00Z',
      },
      {
        id: 'n3-4',
        tags: ['vue', 'templates'],
        title: 'DefineModel Usage',
        pinned: false,
        content: 'Simplify two-way binding with the defineModel macro.',
        completed: true,
        priority: Priority.Easy,
        categoryId: 'cat-003',
        archived: false,
        categoryColor: '#10b981',
        createdAt: '2026-04-26T11:00:00Z',
        updatedAt: '2026-04-26T11:00:00Z',
      },
      {
        id: 'n3-5',
        tags: ['vue', 'logic'],
        title: 'Composables Pattern',
        pinned: false,
        content: 'Strategy for nested composables and state sharing.',
        completed: false,
        priority: Priority.Medium,
        categoryId: 'cat-003',
        archived: false,
        categoryColor: '#10b981',
        createdAt: '2026-04-26T14:00:00Z',
        updatedAt: '2026-04-26T14:00:00Z',
      },
      {
        id: 'n3-6',
        tags: ['vue', 'performance'],
        title: 'ShallowRef Optimization',
        pinned: false,
        content: 'Using shallowRef for large arrays to avoid deep reactivity.',
        completed: true,
        priority: Priority.Medium,
        categoryId: 'cat-003',
        archived: false,
        categoryColor: '#10b981',
        createdAt: '2026-04-25T09:00:00Z',
        updatedAt: '2026-04-25T10:00:00Z',
      },
      {
        id: 'n3-7',
        tags: ['vue', 'async'],
        title: 'Suspense Boundary',
        pinned: false,
        content: 'Experimental: implementing Suspense for async components.',
        completed: false,
        priority: Priority.Hard,
        categoryId: 'cat-003',
        archived: false,
        categoryColor: '#10b981',
        createdAt: '2026-04-25T13:00:00Z',
        updatedAt: '2026-04-25T13:00:00Z',
      },
      {
        id: 'n3-8',
        tags: ['vue', 'dom'],
        title: 'Template Refs with TS',
        pinned: false,
        content: 'Properly typing HTML element refs in setup script.',
        completed: true,
        priority: Priority.Easy,
        categoryId: 'cat-003',
        archived: false,
        categoryColor: '#10b981',
        createdAt: '2026-04-24T10:00:00Z',
        updatedAt: '2026-04-24T10:00:00Z',
      },
      {
        id: 'n3-9',
        tags: ['vue', 'plugins'],
        title: 'App-level Globals',
        pinned: false,
        content: 'How to provide global constants via app.provide.',
        completed: false,
        priority: Priority.Easy,
        categoryId: 'cat-003',
        archived: false,
        categoryColor: '#10b981',
        createdAt: '2026-04-23T15:00:00Z',
        updatedAt: '2026-04-23T15:00:00Z',
      },
      {
        id: 'n3-10',
        tags: ['vue', 'styles'],
        title: 'v-bind in CSS',
        pinned: false,
        content: 'Using reactive variables directly inside <style> blocks.',
        completed: true,
        priority: Priority.Medium,
        categoryId: 'cat-003',
        archived: false,
        categoryColor: '#10b981',
        createdAt: '2026-04-22T12:00:00Z',
        updatedAt: '2026-04-22T12:00:00Z',
      },
    ],
    createdAt: '2026-01-20T12:00:00Z',
    updatedAt: '2026-04-23T08:45:00Z',
  },
  {
    id: 'cat-004',
    name: 'Project Management',
    slug: 'project-management',
    noteCount: 10,
    categoryColor: '#f59e0b',
    categoryNotes: [
      {
        id: 'n4-1',
        tags: ['agile'],
        title: 'Sprint Planning',
        pinned: true,
        content: 'Define tasks for the next development cycle.',
        completed: false,
        priority: Priority.Hard,
        categoryId: 'cat-004',
        archived: false,
        categoryColor: '#f59e0b',
        createdAt: '2026-04-27T09:00:00Z',
        updatedAt: '2026-04-27T09:00:00Z',
      },
      {
        id: 'n4-2',
        tags: ['documentation'],
        title: 'Update README',
        pinned: false,
        content: 'Add installation steps and environment variables guide.',
        completed: true,
        priority: Priority.Medium,
        categoryId: 'cat-004',
        archived: false,
        categoryColor: '#f59e0b',
        createdAt: '2026-04-27T11:00:00Z',
        updatedAt: '2026-04-27T11:30:00Z',
      },
      {
        id: 'n4-3',
        tags: ['client'],
        title: 'Feedback Review',
        pinned: false,
        content: 'Analyze user feedback from the beta testing group.',
        completed: false,
        priority: Priority.Hard,
        categoryId: 'cat-004',
        archived: false,
        categoryColor: '#f59e0b',
        createdAt: '2026-04-27T13:00:00Z',
        updatedAt: '2026-04-27T13:00:00Z',
      },
      {
        id: 'n4-4',
        tags: ['legal'],
        title: 'Privacy Policy',
        pinned: false,
        content: 'Draft initial privacy policy for data storage.',
        completed: false,
        priority: Priority.Medium,
        categoryId: 'cat-004',
        archived: false,
        categoryColor: '#f59e0b',
        createdAt: '2026-04-26T10:00:00Z',
        updatedAt: '2026-04-26T10:00:00Z',
      },
      {
        id: 'n4-5',
        tags: ['tools'],
        title: 'Jira Cleanup',
        pinned: false,
        content: 'Close stale issues and update labels in backlog.',
        completed: true,
        priority: Priority.Easy,
        categoryId: 'cat-004',
        archived: false,
        categoryColor: '#f59e0b',
        createdAt: '2026-04-25T15:00:00Z',
        updatedAt: '2026-04-25T16:00:00Z',
      },
      {
        id: 'n4-6',
        tags: ['hiring'],
        title: 'Intern Interview',
        pinned: false,
        content: 'Prepare technical questions for the junior dev interview.',
        completed: true,
        priority: Priority.Medium,
        categoryId: 'cat-004',
        archived: false,
        categoryColor: '#f59e0b',
        createdAt: '2026-04-25T12:00:00Z',
        updatedAt: '2026-04-25T14:00:00Z',
      },
      {
        id: 'n4-7',
        tags: ['meetings'],
        title: 'Daily Standup',
        pinned: false,
        content: 'Discuss blockers for the dashboard redesign.',
        completed: true,
        priority: Priority.Easy,
        categoryId: 'cat-004',
        archived: false,
        categoryColor: '#f59e0b',
        createdAt: '2026-04-24T09:00:00Z',
        updatedAt: '2026-04-24T09:15:00Z',
      },
      {
        id: 'n4-8',
        tags: ['budget'],
        title: 'SaaS Subscriptions',
        pinned: false,
        content: 'Review and renew Vercel and GitHub Team plans.',
        completed: false,
        priority: Priority.Medium,
        categoryId: 'cat-004',
        archived: false,
        categoryColor: '#f59e0b',
        createdAt: '2026-04-24T11:00:00Z',
        updatedAt: '2026-04-24T11:00:00Z',
      },
      {
        id: 'n4-9',
        tags: ['roadmap'],
        title: 'Q3 Planning',
        pinned: false,
        content: 'Outline key features for the third quarter.',
        completed: false,
        priority: Priority.Hard,
        categoryId: 'cat-004',
        archived: false,
        categoryColor: '#f59e0b',
        createdAt: '2026-04-23T14:00:00Z',
        updatedAt: '2026-04-23T14:00:00Z',
      },
      {
        id: 'n4-10',
        tags: ['assets'],
        title: 'Domain Renewal',
        pinned: false,
        content: 'Ensure auto-renewal is active for the primary domain.',
        completed: true,
        priority: Priority.Easy,
        categoryId: 'cat-004',
        archived: false,
        categoryColor: '#f59e0b',
        createdAt: '2026-04-22T10:00:00Z',
        updatedAt: '2026-04-22T10:00:00Z',
      },
    ],
    createdAt: '2026-03-05T16:20:00Z',
    updatedAt: '2026-03-10T10:10:00Z',
  },
  {
    id: 'cat-005',
    name: 'Global State Pinia',
    slug: 'global-state-pinia',
    noteCount: 10,
    categoryColor: '#ef4444',
    categoryNotes: [
      {
        id: 'n5-1',
        tags: ['pinia', 'setup'],
        title: 'Option vs Setup Store',
        pinned: true,
        content: 'Comparative analysis of store definitions.',
        completed: true,
        priority: Priority.Easy,
        categoryId: 'cat-005',
        archived: false,
        categoryColor: '#ef4444',
        createdAt: '2026-04-20T09:00:00Z',
        updatedAt: '2026-04-20T09:00:00Z',
      },
      {
        id: 'n5-2',
        tags: ['pinia', 'persistance'],
        title: 'Local Storage Sync',
        pinned: false,
        content: 'Implement pinia-plugin-persistedstate for user settings.',
        completed: false,
        priority: Priority.Medium,
        categoryId: 'cat-005',
        archived: false,
        categoryColor: '#ef4444',
        createdAt: '2026-04-20T11:00:00Z',
        updatedAt: '2026-04-20T11:00:00Z',
      },
      {
        id: 'n5-3',
        tags: ['pinia', 'actions'],
        title: 'Async Actions Pattern',
        pinned: false,
        content: 'Best practices for handling try/catch inside Pinia actions.',
        completed: false,
        priority: Priority.Hard,
        categoryId: 'cat-005',
        archived: false,
        categoryColor: '#ef4444',
        createdAt: '2026-04-21T10:00:00Z',
        updatedAt: '2026-04-21T10:00:00Z',
      },
      {
        id: 'n5-4',
        tags: ['pinia', 'getters'],
        title: 'Dynamic Getters',
        pinned: false,
        content: 'How to pass arguments to getters for filtered results.',
        completed: true,
        priority: Priority.Medium,
        categoryId: 'cat-005',
        archived: false,
        categoryColor: '#ef4444',
        createdAt: '2026-04-21T13:00:00Z',
        updatedAt: '2026-04-21T13:00:00Z',
      },
      {
        id: 'n5-5',
        tags: ['pinia', 'testing'],
        title: 'Store Mocking',
        pinned: false,
        content: 'Setup createTestingPinia for component unit tests.',
        completed: false,
        priority: Priority.Hard,
        categoryId: 'cat-005',
        archived: false,
        categoryColor: '#ef4444',
        createdAt: '2026-04-22T08:00:00Z',
        updatedAt: '2026-04-22T08:00:00Z',
      },
      {
        id: 'n5-6',
        tags: ['pinia', 'modular'],
        title: 'Splitting Large Stores',
        pinned: false,
        content: 'Guidelines for store decomposition and cross-store calls.',
        completed: false,
        priority: Priority.Medium,
        categoryId: 'cat-005',
        archived: false,
        categoryColor: '#ef4444',
        createdAt: '2026-04-22T15:00:00Z',
        updatedAt: '2026-04-22T15:00:00Z',
      },
      {
        id: 'n5-7',
        tags: ['pinia', 'ssr'],
        title: 'Hydration Strategy',
        pinned: false,
        content: 'Managing store hydration in Nuxt 3 environments.',
        completed: false,
        priority: Priority.Hard,
        categoryId: 'cat-005',
        archived: false,
        categoryColor: '#ef4444',
        createdAt: '2026-04-23T10:00:00Z',
        updatedAt: '2026-04-23T10:00:00Z',
      },
      {
        id: 'n5-8',
        tags: ['pinia', 'reactivity'],
        title: 'StoreToRefs Gotchas',
        pinned: false,
        content: 'Why destructured store data loses reactivity.',
        completed: true,
        priority: Priority.Easy,
        categoryId: 'cat-005',
        archived: false,
        categoryColor: '#ef4444',
        createdAt: '2026-04-23T14:00:00Z',
        updatedAt: '2026-04-23T14:00:00Z',
      },
      {
        id: 'n5-9',
        tags: ['pinia', 'api'],
        title: '$reset and $patch',
        pinned: false,
        content: 'Bulk updates vs direct state mutations.',
        completed: true,
        priority: Priority.Easy,
        categoryId: 'cat-005',
        archived: false,
        categoryColor: '#ef4444',
        createdAt: '2026-04-24T09:00:00Z',
        updatedAt: '2026-04-24T09:00:00Z',
      },
      {
        id: 'n5-10',
        tags: ['pinia', 'dev-tools'],
        title: 'Customizing DevTools',
        pinned: false,
        content: 'Adding custom properties to the Pinia inspector.',
        completed: false,
        priority: Priority.Medium,
        categoryId: 'cat-005',
        archived: false,
        categoryColor: '#ef4444',
        createdAt: '2026-04-24T12:00:00Z',
        updatedAt: '2026-04-24T12:00:00Z',
      },
    ],
    createdAt: '2026-02-28T14:00:00Z',
    updatedAt: '2026-04-15T13:20:00Z',
  },
  {
    id: 'cat-006',
    name: 'Web Accessibility',
    slug: 'web-accessibility',
    noteCount: 10,
    categoryColor: '#ec4899',
    categoryNotes: [
      {
        id: 'n6-1',
        tags: ['a11y', 'html'],
        title: 'Semantic Markup',
        pinned: true,
        content: 'Check all button elements for proper aria-labels.',
        completed: false,
        priority: Priority.Hard,
        categoryId: 'cat-006',
        archived: false,
        categoryColor: '#ec4899',
        createdAt: '2026-03-15T12:00:00Z',
        updatedAt: '2026-03-15T12:00:00Z',
      },
      {
        id: 'n6-2',
        tags: ['a11y', 'focus'],
        title: 'Keyboard Navigation',
        pinned: false,
        content: 'Ensure all interactive elements are focusable.',
        completed: true,
        priority: Priority.Hard,
        categoryId: 'cat-006',
        archived: false,
        categoryColor: '#ec4899',
        createdAt: '2026-03-16T10:00:00Z',
        updatedAt: '2026-03-16T11:00:00Z',
      },
      {
        id: 'n6-3',
        tags: ['a11y', 'colors'],
        title: 'Contrast Ratio',
        pinned: false,
        content: 'Verify WCAG AA compliance for the primary color palette.',
        completed: true,
        priority: Priority.Medium,
        categoryId: 'cat-006',
        archived: false,
        categoryColor: '#ec4899',
        createdAt: '2026-03-17T09:00:00Z',
        updatedAt: '2026-03-17T09:00:00Z',
      },
      {
        id: 'n6-4',
        tags: ['a11y', 'images'],
        title: 'Alt Text Audit',
        pinned: false,
        content: 'Missing alt tags on hero images in the blog section.',
        completed: false,
        priority: Priority.Easy,
        categoryId: 'cat-006',
        archived: false,
        categoryColor: '#ec4899',
        createdAt: '2026-03-18T14:00:00Z',
        updatedAt: '2026-03-18T14:00:00Z',
      },
      {
        id: 'n6-5',
        tags: ['a11y', 'screen-readers'],
        title: 'Aria Live Regions',
        pinned: false,
        content: 'Implement aria-live for notification toasts.',
        completed: false,
        priority: Priority.Medium,
        categoryId: 'cat-006',
        archived: false,
        categoryColor: '#ec4899',
        createdAt: '2026-03-19T10:00:00Z',
        updatedAt: '2026-03-19T10:00:00Z',
      },
      {
        id: 'n6-6',
        tags: ['a11y', 'forms'],
        title: 'Label Associations',
        pinned: false,
        content: 'Fix explicit labels for the contact form inputs.',
        completed: true,
        priority: Priority.Medium,
        categoryId: 'cat-006',
        archived: false,
        categoryColor: '#ec4899',
        createdAt: '2026-03-20T11:00:00Z',
        updatedAt: '2026-03-20T11:30:00Z',
      },
      {
        id: 'n6-7',
        tags: ['a11y', 'testing'],
        title: 'Lighthouse Check',
        pinned: false,
        content: 'Run automated accessibility tests on the landing page.',
        completed: true,
        priority: Priority.Easy,
        categoryId: 'cat-006',
        archived: false,
        categoryColor: '#ec4899',
        createdAt: '2026-03-21T09:00:00Z',
        updatedAt: '2026-03-21T09:30:00Z',
      },
      {
        id: 'n6-8',
        tags: ['a11y', 'motion'],
        title: 'Reduced Motion',
        pinned: false,
        content: 'Support prefers-reduced-motion CSS media query.',
        completed: false,
        priority: Priority.Easy,
        categoryId: 'cat-006',
        archived: false,
        categoryColor: '#ec4899',
        createdAt: '2026-03-22T13:00:00Z',
        updatedAt: '2026-03-22T13:00:00Z',
      },
      {
        id: 'n6-9',
        tags: ['a11y', 'navigation'],
        title: 'Skip to Content Link',
        pinned: false,
        content: 'Add a skip link for keyboard users in the header.',
        completed: false,
        priority: Priority.Medium,
        categoryId: 'cat-006',
        archived: false,
        categoryColor: '#ec4899',
        createdAt: '2026-03-23T15:00:00Z',
        updatedAt: '2026-03-23T15:00:00Z',
      },
      {
        id: 'n6-10',
        tags: ['a11y', 'tables'],
        title: 'Table Semantics',
        pinned: false,
        content: 'Verify scope="col" and captions for data tables.',
        completed: false,
        priority: Priority.Easy,
        categoryId: 'cat-006',
        archived: false,
        categoryColor: '#ec4899',
        createdAt: '2026-03-24T10:00:00Z',
        updatedAt: '2026-03-24T10:00:00Z',
      },
    ],
    createdAt: '2026-03-15T11:30:00Z',
    updatedAt: '2026-03-20T09:00:00Z',
  },
  {
    id: 'cat-007',
    name: 'Server Side Rendering',
    slug: 'ssr-guide',
    noteCount: 10,
    categoryColor: '#06b6d4',
    categoryNotes: [
      {
        id: 'n7-1',
        tags: ['ssr', 'nuxt'],
        title: 'Universal Rendering',
        pinned: true,
        content: 'Configuring hybrid rendering in Nuxt 3.',
        completed: true,
        priority: Priority.Hard,
        categoryId: 'cat-007',
        archived: false,
        categoryColor: '#06b6d4',
        createdAt: '2026-04-01T10:00:00Z',
        updatedAt: '2026-04-01T10:00:00Z',
      },
      {
        id: 'n7-2',
        tags: ['ssr', 'seo'],
        title: 'Dynamic Meta Tags',
        pinned: false,
        content: 'Use useHead for dynamic title and description.',
        completed: false,
        priority: Priority.Medium,
        categoryId: 'cat-007',
        archived: false,
        categoryColor: '#06b6d4',
        createdAt: '2026-04-01T12:00:00Z',
        updatedAt: '2026-04-01T12:00:00Z',
      },
      {
        id: 'n7-3',
        tags: ['ssr', 'api'],
        title: 'Fetch vs AsyncData',
        pinned: false,
        content: 'Key differences for server-side data fetching.',
        completed: true,
        priority: Priority.Medium,
        categoryId: 'cat-007',
        archived: false,
        categoryColor: '#06b6d4',
        createdAt: '2026-04-02T09:00:00Z',
        updatedAt: '2026-04-02T10:00:00Z',
      },
      {
        id: 'n7-4',
        tags: ['ssr', 'auth'],
        title: 'Cookie-based Auth',
        pinned: false,
        content: 'Handling JWT tokens on the server and client.',
        completed: false,
        priority: Priority.Hard,
        categoryId: 'cat-007',
        archived: false,
        categoryColor: '#06b6d4',
        createdAt: '2026-04-03T11:00:00Z',
        updatedAt: '2026-04-03T11:00:00Z',
      },
      {
        id: 'n7-5',
        tags: ['ssr', 'caching'],
        title: 'SWR Strategies',
        pinned: false,
        content: 'Implementing Stale-While-Revalidate headers.',
        completed: false,
        priority: Priority.Medium,
        categoryId: 'cat-007',
        archived: false,
        categoryColor: '#06b6d4',
        createdAt: '2026-04-04T15:00:00Z',
        updatedAt: '2026-04-04T15:00:00Z',
      },
      {
        id: 'n7-6',
        tags: ['ssr', 'performance'],
        title: 'Critical CSS',
        pinned: false,
        content: 'Extracting and inlining critical styles.',
        completed: true,
        priority: Priority.Hard,
        categoryId: 'cat-007',
        archived: false,
        categoryColor: '#06b6d4',
        createdAt: '2026-04-05T10:00:00Z',
        updatedAt: '2026-04-05T10:00:00Z',
      },
      {
        id: 'n7-7',
        tags: ['ssr', 'errors'],
        title: 'SSR Error Handling',
        pinned: false,
        content: 'Custom 500 error pages for rendering failures.',
        completed: false,
        priority: Priority.Medium,
        categoryId: 'cat-007',
        archived: false,
        categoryColor: '#06b6d4',
        createdAt: '2026-04-06T14:00:00Z',
        updatedAt: '2026-04-06T14:00:00Z',
      },
      {
        id: 'n7-8',
        tags: ['ssr', 'client-only'],
        title: 'ClientOnly Component',
        pinned: false,
        content: 'Wrapping non-SSR compatible libraries.',
        completed: true,
        priority: Priority.Easy,
        categoryId: 'cat-007',
        archived: false,
        categoryColor: '#06b6d4',
        createdAt: '2026-04-07T09:00:00Z',
        updatedAt: '2026-04-07T09:00:00Z',
      },
      {
        id: 'n7-9',
        tags: ['ssr', 'node'],
        title: 'Server Middleware',
        pinned: false,
        content: 'Setting up custom H3 event handlers in Nuxt.',
        completed: false,
        priority: Priority.Medium,
        categoryId: 'cat-007',
        archived: false,
        categoryColor: '#06b6d4',
        createdAt: '2026-04-08T13:00:00Z',
        updatedAt: '2026-04-08T13:00:00Z',
      },
      {
        id: 'n7-10',
        tags: ['ssr', 'deployment'],
        title: 'Nitro Deployment',
        pinned: false,
        content: 'Configuring Nitro for Vercel Edge Functions.',
        completed: false,
        priority: Priority.Hard,
        categoryId: 'cat-007',
        archived: false,
        categoryColor: '#06b6d4',
        createdAt: '2026-04-09T16:00:00Z',
        updatedAt: '2026-04-09T16:00:00Z',
      },
    ],
    createdAt: '2026-01-05T08:45:00Z',
    updatedAt: '2026-04-01T17:50:00Z',
  },
  {
    id: 'cat-008',
    name: 'Unit Testing Vitest',
    slug: 'unit-testing-vitest',
    noteCount: 10,
    categoryColor: '#6366f1',
    categoryNotes: [
      {
        id: 'n8-1',
        tags: ['testing', 'setup'],
        title: 'Vitest Config',
        pinned: true,
        content: 'Configure global setup and aliases for tests.',
        completed: true,
        priority: Priority.Easy,
        categoryId: 'cat-008',
        archived: false,
        categoryColor: '#6366f1',
        createdAt: '2026-04-18T10:00:00Z',
        updatedAt: '2026-04-18T10:00:00Z',
      },
      {
        id: 'n8-2',
        tags: ['testing', 'vue'],
        title: 'Component Mounts',
        pinned: false,
        content: 'Differences between mount and shallowMount.',
        completed: false,
        priority: Priority.Medium,
        categoryId: 'cat-008',
        archived: false,
        categoryColor: '#6366f1',
        createdAt: '2026-04-18T12:00:00Z',
        updatedAt: '2026-04-18T12:00:00Z',
      },
      {
        id: 'n8-3',
        tags: ['testing', 'mocks'],
        title: 'Mocking Axios',
        pinned: false,
        content: 'Using vi.mock to simulate API responses.',
        completed: true,
        priority: Priority.Hard,
        categoryId: 'cat-008',
        archived: false,
        categoryColor: '#6366f1',
        createdAt: '2026-04-19T09:00:00Z',
        updatedAt: '2026-04-19T09:00:00Z',
      },
      {
        id: 'n8-4',
        tags: ['testing', 'coverage'],
        title: 'Coverage Reports',
        pinned: false,
        content: 'Enable V8 coverage tool and set thresholds.',
        completed: false,
        priority: Priority.Medium,
        categoryId: 'cat-008',
        archived: false,
        categoryColor: '#6366f1',
        createdAt: '2026-04-19T14:00:00Z',
        updatedAt: '2026-04-19T14:00:00Z',
      },
      {
        id: 'n8-5',
        tags: ['testing', 'async'],
        title: 'Testing Async Logic',
        pinned: false,
        content: 'Using flushPromises and nextTick in Vue tests.',
        completed: false,
        priority: Priority.Hard,
        categoryId: 'cat-008',
        archived: false,
        categoryColor: '#6366f1',
        createdAt: '2026-04-20T11:00:00Z',
        updatedAt: '2026-04-20T11:00:00Z',
      },
      {
        id: 'n8-6',
        tags: ['testing', 'events'],
        title: 'Emit Verification',
        pinned: false,
        content: 'Check if component emits correct events with data.',
        completed: true,
        priority: Priority.Easy,
        categoryId: 'cat-008',
        archived: false,
        categoryColor: '#6366f1',
        createdAt: '2026-04-20T15:00:00Z',
        updatedAt: '2026-04-20T15:00:00Z',
      },
      {
        id: 'n8-7',
        tags: ['testing', 'snaphots'],
        title: 'Snapshot Testing',
        pinned: false,
        content: 'When to use snapshots for UI components.',
        completed: false,
        priority: Priority.Easy,
        categoryId: 'cat-008',
        archived: false,
        categoryColor: '#6366f1',
        createdAt: '2026-04-21T09:00:00Z',
        updatedAt: '2026-04-21T09:00:00Z',
      },
      {
        id: 'n8-8',
        tags: ['testing', 'hooks'],
        title: 'Composables Testing',
        pinned: false,
        content: 'Testing reactive logic in isolation.',
        completed: true,
        priority: Priority.Medium,
        categoryId: 'cat-008',
        archived: false,
        categoryColor: '#6366f1',
        createdAt: '2026-04-21T13:00:00Z',
        updatedAt: '2026-04-21T13:00:00Z',
      },
      {
        id: 'n8-9',
        tags: ['testing', 'timers'],
        title: 'vi.useFakeTimers',
        pinned: false,
        content: 'Handling setTimeout and debounce in unit tests.',
        completed: false,
        priority: Priority.Medium,
        categoryId: 'cat-008',
        archived: false,
        categoryColor: '#6366f1',
        createdAt: '2026-04-22T10:00:00Z',
        updatedAt: '2026-04-22T10:00:00Z',
      },
      {
        id: 'n8-10',
        tags: ['testing', 'ci'],
        title: 'GitHub Actions Test',
        pinned: false,
        content: 'Running Vitest in head-less mode on CI pipeline.',
        completed: false,
        priority: Priority.Hard,
        categoryId: 'cat-008',
        archived: false,
        categoryColor: '#6366f1',
        createdAt: '2026-04-22T16:00:00Z',
        updatedAt: '2026-04-22T16:00:00Z',
      },
    ],
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-04-18T12:15:00Z',
  },
  {
    id: 'cat-009',
    name: 'Performance Tuning',
    slug: 'performance-tuning',
    noteCount: 10,
    categoryColor: '#84cc16',
    categoryNotes: [
      {
        id: 'n9-1',
        tags: ['perf', 'images'],
        title: 'Lazy Loading Images',
        pinned: true,
        content: 'Implement native loading="lazy" for all gallery items.',
        completed: true,
        priority: Priority.Easy,
        categoryId: 'cat-009',
        archived: false,
        categoryColor: '#84cc16',
        createdAt: '2026-04-21T10:00:00Z',
        updatedAt: '2026-04-21T10:00:00Z',
      },
      {
        id: 'n9-2',
        tags: ['perf', 'code-splitting'],
        title: 'Async Components',
        pinned: false,
        content: 'Lazy load heavy modal and chart components.',
        completed: false,
        priority: Priority.Hard,
        categoryId: 'cat-009',
        archived: false,
        categoryColor: '#84cc16',
        createdAt: '2026-04-21T12:00:00Z',
        updatedAt: '2026-04-21T12:00:00Z',
      },
      {
        id: 'n9-3',
        tags: ['perf', 'fonts'],
        title: 'Font Optimization',
        pinned: false,
        content: 'Switch to woff2 and add font-display: swap.',
        completed: true,
        priority: Priority.Medium,
        categoryId: 'cat-009',
        archived: false,
        categoryColor: '#84cc16',
        createdAt: '2026-04-22T09:00:00Z',
        updatedAt: '2026-04-22T09:00:00Z',
      },
      {
        id: 'n9-4',
        tags: ['perf', 'memo'],
        title: 'React v-memo',
        pinned: false,
        content: 'Using v-memo to skip re-renders for static list parts.',
        completed: false,
        priority: Priority.Medium,
        categoryId: 'cat-009',
        archived: false,
        categoryColor: '#84cc16',
        createdAt: '2026-04-22T14:00:00Z',
        updatedAt: '2026-04-22T14:00:00Z',
      },
      {
        id: 'n9-5',
        tags: ['perf', 'bundles'],
        title: 'Analyze Bundle',
        pinned: false,
        content: 'Use rollup-plugin-visualizer to find large dependencies.',
        completed: true,
        priority: Priority.Hard,
        categoryId: 'cat-009',
        archived: false,
        categoryColor: '#84cc16',
        createdAt: '2026-04-23T10:00:00Z',
        updatedAt: '2026-04-23T11:00:00Z',
      },
      {
        id: 'n9-6',
        tags: ['perf', 'network'],
        title: 'Prefetching Assets',
        pinned: false,
        content: 'Add <link rel="prefetch"> for next-page resources.',
        completed: false,
        priority: Priority.Easy,
        categoryId: 'cat-009',
        archived: false,
        categoryColor: '#84cc16',
        createdAt: '2026-04-23T15:00:00Z',
        updatedAt: '2026-04-23T15:00:00Z',
      },
      {
        id: 'n9-7',
        tags: ['perf', 'execution'],
        title: 'Web Workers',
        pinned: false,
        content: 'Move heavy data processing to a background worker.',
        completed: false,
        priority: Priority.Hard,
        categoryId: 'cat-009',
        archived: false,
        categoryColor: '#84cc16',
        createdAt: '2026-04-24T08:00:00Z',
        updatedAt: '2026-04-24T08:00:00Z',
      },
      {
        id: 'n9-8',
        tags: ['perf', 'css'],
        title: 'Purge Unused CSS',
        pinned: false,
        content: 'Review Tailwind config to remove unused class generation.',
        completed: true,
        priority: Priority.Medium,
        categoryId: 'cat-009',
        archived: false,
        categoryColor: '#84cc16',
        createdAt: '2026-04-24T11:00:00Z',
        updatedAt: '2026-04-24T11:00:00Z',
      },
      {
        id: 'n9-9',
        tags: ['perf', 'vitals'],
        title: 'Core Web Vitals',
        pinned: false,
        content: 'Improving LCP score by preloading the hero image.',
        completed: false,
        priority: Priority.Hard,
        categoryId: 'cat-009',
        archived: false,
        categoryColor: '#84cc16',
        createdAt: '2026-04-25T09:00:00Z',
        updatedAt: '2026-04-25T09:00:00Z',
      },
      {
        id: 'n9-10',
        tags: ['perf', 'cleanup'],
        title: 'Memory Leaks',
        pinned: false,
        content: 'Audit EventListeners in unmounted components.',
        completed: false,
        priority: Priority.Medium,
        categoryId: 'cat-009',
        archived: false,
        categoryColor: '#84cc16',
        createdAt: '2026-04-25T14:00:00Z',
        updatedAt: '2026-04-25T14:00:00Z',
      },
    ],
    createdAt: '2026-03-20T13:10:00Z',
    updatedAt: '2026-04-21T15:40:00Z',
  },
  {
    id: 'cat-010',
    name: 'Continuous Integration',
    slug: 'ci-cd-pipeline',
    noteCount: 10,
    categoryColor: '#f97316',
    categoryNotes: [
      {
        id: 'n10-1',
        tags: ['ci', 'gh-actions'],
        title: 'Build Workflow',
        pinned: true,
        content: 'Trigger production build on main branch push.',
        completed: true,
        priority: Priority.Hard,
        categoryId: 'cat-010',
        archived: false,
        categoryColor: '#f97316',
        createdAt: '2026-04-23T12:00:00Z',
        updatedAt: '2026-04-23T12:00:00Z',
      },
      {
        id: 'n10-2',
        tags: ['ci', 'lint'],
        title: 'Lint Check',
        pinned: false,
        content: 'Run ESLint as a required check for PRs.',
        completed: true,
        priority: Priority.Medium,
        categoryId: 'cat-010',
        archived: false,
        categoryColor: '#f97316',
        createdAt: '2026-04-23T14:00:00Z',
        updatedAt: '2026-04-23T14:00:00Z',
      },
      {
        id: 'n10-3',
        tags: ['ci', 'deployment'],
        title: 'Vercel Integration',
        pinned: false,
        content: 'Setup preview deployments for each pull request.',
        completed: true,
        priority: Priority.Easy,
        categoryId: 'cat-010',
        archived: false,
        categoryColor: '#f97316',
        createdAt: '2026-04-24T09:00:00Z',
        updatedAt: '2026-04-24T09:00:00Z',
      },
      {
        id: 'n10-4',
        tags: ['ci', 'security'],
        title: 'Secrets Management',
        pinned: false,
        content: 'Migrate environment variables to GitHub Secrets.',
        completed: false,
        priority: Priority.Hard,
        categoryId: 'cat-010',
        archived: false,
        categoryColor: '#f97316',
        createdAt: '2026-04-24T12:00:00Z',
        updatedAt: '2026-04-24T12:00:00Z',
      },
      {
        id: 'n10-5',
        tags: ['ci', 'artifacts'],
        title: 'Build Artifacts',
        pinned: false,
        content: 'Archive build dist folder for troubleshooting.',
        completed: false,
        priority: Priority.Easy,
        categoryId: 'cat-010',
        archived: false,
        categoryColor: '#f97316',
        createdAt: '2026-04-25T10:00:00Z',
        updatedAt: '2026-04-25T10:00:00Z',
      },
      {
        id: 'n10-6',
        tags: ['ci', 'notifications'],
        title: 'Slack Webhooks',
        pinned: false,
        content: 'Notify the team on failed CI pipeline runs.',
        completed: false,
        priority: Priority.Medium,
        categoryId: 'cat-010',
        archived: false,
        categoryColor: '#f97316',
        createdAt: '2026-04-25T15:00:00Z',
        updatedAt: '2026-04-25T15:00:00Z',
      },
      {
        id: 'n10-7',
        tags: ['ci', 'cache'],
        title: 'PNPM Cache',
        pinned: false,
        content: 'Optimization: cache node_modules for faster builds.',
        completed: true,
        priority: Priority.Medium,
        categoryId: 'cat-010',
        archived: false,
        categoryColor: '#f97316',
        createdAt: '2026-04-26T08:00:00Z',
        updatedAt: '2026-04-26T08:00:00Z',
      },
      {
        id: 'n10-8',
        tags: ['ci', 'docker'],
        title: 'Docker Build Check',
        pinned: false,
        content: 'Ensure Docker images build correctly on production tags.',
        completed: false,
        priority: Priority.Hard,
        categoryId: 'cat-010',
        archived: false,
        categoryColor: '#f97316',
        createdAt: '2026-04-26T13:00:00Z',
        updatedAt: '2026-04-26T13:00:00Z',
      },
      {
        id: 'n10-9',
        tags: ['ci', 'lighthouse'],
        title: 'Lighthouse CI',
        pinned: false,
        content: 'Automatically check performance budget on build.',
        completed: false,
        priority: Priority.Medium,
        categoryId: 'cat-010',
        archived: false,
        categoryColor: '#f97316',
        createdAt: '2026-04-27T10:00:00Z',
        updatedAt: '2026-04-27T10:00:00Z',
      },
      {
        id: 'n10-10',
        tags: ['ci', 'versioning'],
        title: 'Auto Semantic Release',
        pinned: false,
        content: 'Setup automatic versioning based on commit messages.',
        completed: false,
        priority: Priority.Hard,
        categoryId: 'cat-010',
        archived: false,
        categoryColor: '#f97316',
        createdAt: '2026-04-27T14:00:00Z',
        updatedAt: '2026-04-27T14:00:00Z',
      },
    ],
    createdAt: '2026-04-10T11:00:00Z',
    updatedAt: '2026-04-23T12:00:00Z',
  },
];
